# Copyright (c) the JPEG XL Project Authors. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Workflow for building and running tests.

name: Build/Test MSYS2
on:
  push:
    branches:
      - main

permissions:
  contents: read
  
jobs:
  build_test:
    name: Windows MSYS2 / ${{ matrix.msystem }}
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'CI:none') }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
         - msystem: mingw64
           disable_tests:
             - ButteraugliTest.Lossless
             - ButteraugliTest.Distmap
             - JxlTest.RoundtripLargeEmptyModular
           disable_benchmark: true
           
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout the source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          fetch-depth: 1

      - uses: msys2/setup-msys2@07aeda7763550b267746a772dcea5e5ac3340b36 # v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          path-type: inherit
          install: >-
            base-devel
            git
            procps
          pacboy: >-
            brotli:p
            cmake:p
            giflib:p
            gtest:p
            libavif:p
            libjpeg-turbo:p
            libpng:p
            libwebp:p
            ninja:p
            toolchain:p

      - name: CMake configure
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DJPEGXL_ENABLE_JNI=OFF \
            -DJPEGXL_ENABLE_MANPAGES=OFF \
            -DJPEGXL_FORCE_SYSTEM_BROTLI=ON \
            -DJPEGXL_FORCE_SYSTEM_GTEST=ON \
            -B build \
            -G Ninja

      - name: CMake build
        run: cmake --build build
        
      - uses: milliewalky/setup-7-zip@v2
        with:
          tag: "latest"

      - name: zip artifacts
        run: 7z a build.7z ./build

      - name: Upload build.7z as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-archive
          path: build.7z
